version: "3.8"

services:
  db:
    image: postgres:15
    container_name: food_db
    restart: always
    ports:
      - '5454:5432'
    environment:
      POSTGRES_DB: FOOD
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - food_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"

networks:
  food_network: